library("ggplot2")
library("dplyr")

# Load bootstrap survival curves summary
# This file is generated by bootstrap_noreplace.R
output_dir <- "bootstrap_results"  # Update this to match your bootstrap output directory
survcurves_summary_file <- file.path(output_dir, "bootstrap_survival_curves_summary.csv")

if (!file.exists(survcurves_summary_file)) {
  stop(sprintf("Survival curves summary file not found: %s\nPlease run bootstrap_noreplace.R first.", survcurves_summary_file))
}

surv_summary <- read.csv(survcurves_summary_file)

# Theme matching the original plot style
big_axis <- theme(
  axis.title = element_text(size = 40),
  axis.text  = element_text(size = 28),
  legend.title = element_text(size = 28),
  legend.text  = element_text(size = 28)
)

# Function to create survival curve plot with bootstrap CIs
# Matches the style of plot_survival_curves_final_clean.R
create_survival_plot <- function(data, model_name, title = NULL) {
  # Prepare data for plotting
  # We need to create separate rows for treatment 0 (ACEi) and treatment 1 (Thiazide)
  plot_data <- bind_rows(
    data %>%
      select(time, surv = surv0_mean, ci_lower = surv0_CI_lower, ci_upper = surv0_CI_upper) %>%
      mutate(Treatment = "ACEi"),
    data %>%
      select(time, surv = surv1_mean, ci_lower = surv1_CI_lower, ci_upper = surv1_CI_upper) %>%
      mutate(Treatment = "Thiazide")
  )
  
  # Create the plot matching ggsurvplot style
  # Using default ggplot2 colors (similar to ggsurvplot defaults)
  p <- ggplot(plot_data, aes(x = time, y = surv, color = Treatment, linetype = Treatment)) +
    geom_line(size = 1.2) +
    geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper, fill = Treatment), 
                alpha = 0.2, linetype = 0, show.legend = FALSE) +
    scale_color_manual(values = c("ACEi" = "#E7B800", "Thiazide" = "#2E9FDF"),
                      labels = c("ACEi", "Thiazide")) +
    scale_fill_manual(values = c("ACEi" = "#E7B800", "Thiazide" = "#2E9FDF"),
                     guide = "none") +
    scale_linetype_manual(values = c("ACEi" = "solid", "Thiazide" = "dashed"),
                         labels = c("ACEi", "Thiazide")) +
    labs(x = "Time (days)", 
         y = "Survival Probability",
         color = "Treatment",
         linetype = "Treatment") +
    theme_bw() + 
    big_axis +
    theme(legend.position = "bottom",
          legend.direction = "horizontal",
          legend.box = "horizontal") +
    ylim(0.85, 1) +
    xlim(0, max(plot_data$time, na.rm = TRUE))
  
  return(p)
}

# Create plots for each model (matching the order in plot_survival_curves_final_clean.R)

# NO ADJUSTMENT
unadj_data <- surv_summary %>%
  filter(model == "unadjusted") %>%
  arrange(time)

if (nrow(unadj_data) > 0) {
  unadj.plot <- create_survival_plot(unadj_data, "unadjusted")
  print(unadj.plot)
  
  ggsave("unadjusted_plot.png", unadj.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_unadjusted_plot.pdf", unadj.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: unadjusted_plot.png and RWD_unadjusted_plot.pdf\n")
}

# IPTW
iptw_data <- surv_summary %>%
  filter(model == "iptw") %>%
  arrange(time)

if (nrow(iptw_data) > 0) {
  iptw.plot <- create_survival_plot(iptw_data, "iptw")
  print(iptw.plot)
  
  ggsave("iptw_plot.png", iptw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_iptw_plot.pdf", iptw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: iptw_plot.png and RWD_iptw_plot.pdf\n")
}

# IPCW
ipcw_data <- surv_summary %>%
  filter(model == "ipcw") %>%
  arrange(time)

if (nrow(ipcw_data) > 0) {
  ipcw.plot <- create_survival_plot(ipcw_data, "ipcw")
  print(ipcw.plot)
  
  ggsave("ipcw_plot.png", ipcw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_ipcw_plot.pdf", ipcw.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: ipcw_plot.png and RWD_ipcw_plot.pdf\n")
}

# COMBINED
comb_data <- surv_summary %>%
  filter(model == "combined") %>%
  arrange(time)

if (nrow(comb_data) > 0) {
  comb.plot <- create_survival_plot(comb_data, "combined")
  print(comb.plot)
  
  ggsave("comb_plot.png", comb.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  ggsave("RWD_comb_plot.pdf", comb.plot, 
         width = 11, 
         height = 7,
         dpi = 600)
  cat("Saved: comb_plot.png and RWD_comb_plot.pdf\n")
}

cat("\nAll survival curve plots have been generated and saved.\n")
